using System.Collections.Generic;
using System.Linq;

namespace Celeste.Mod.SpeedrunTool.TeleportRoom;

public record struct ReorderedName(string LevelName, Vector2? RespawnPoint = null) {
    public readonly string LevelName = LevelName;
    public readonly Vector2? RespawnPoint = RespawnPoint;

    public ReorderedName(string levelName, float x, float y) : this(levelName, new Vector2(x, y)) { }
}

public record struct ReorderedData(LevelData LevelData, Vector2? RespawnPoint = null) {
    public readonly LevelData LevelData = LevelData;
    public readonly Vector2? RespawnPoint = RespawnPoint;
}

public static class LevelDataReorderUtils {
    private static readonly Dictionary<TeleportRoomCategory, Dictionary<string, List<ReorderedName>>> ReorderedDataDict = new() {
        {
            TeleportRoomCategory.Default, new Dictionary<string, List<ReorderedName>> {
                {
                    "Celeste/0-Intro-Normal",
                    new List<ReorderedName> {
                        new("-1"),
                        new("0"),
                        new("0b"),
                        new("1"),
                        new("2"),
                        new("3"),
                        new("x1"),
                    }
                }, {
                    "Celeste/1-ForsakenCity-Normal",
                    new List<ReorderedName> {
                        new("1"),
                        new("2"),
                        new("3"),
                        new("4"),
                        new("3b"),
                        new("5"),
                        new("5z"),
                        new("5a"),
                        new("6"),
                        new("6z"),
                        new("7zb"),
                        new("6zb"),
                        new("6a"),
                        new("6b"),
                        new("s0"),
                        new("s1"),
                        new("6c"),
                        new("7z"),
                        new("8z"),
                        new("8zb"),
                        new("7"),
                        new("8"),
                        new("7a"),
                        new("9z"),
                        new("8b"),
                        new("9"),
                        new("9b"),
                        new("9c"),
                        new("10"),
                        new("10z"),
                        new("10zb"),
                        new("11"),
                        new("11z"),
                        new("10a"),
                        new("12"),
                        new("12z"),
                        new("12a"),
                        new("end"),
                    }
                }, {
                    "Celeste/1-ForsakenCity-BSide",
                    new List<ReorderedName> {
                        new("00"),
                        new("01"),
                        new("02"),
                        new("02b"),
                        new("03"),
                        new("04"),
                        new("05"),
                        new("05b"),
                        new("06"),
                        new("07"),
                        new("08"),
                        new("08b"),
                        new("09"),
                        new("10"),
                        new("11"),
                        new("end"),
                    }
                }, {
                    "Celeste/1-ForsakenCity-CSide",
                    new List<ReorderedName> {
                        new("00"),
                        new("01"),
                        new("02"),
                    }
                }, {
                    "Celeste/2-OldSite-Normal",
                    new List<ReorderedName> {
                        new("start"),
                        new("s0"),
                        new("s1"),
                        new("s2"),
                        new("0"),
                        new("1"),
                        new("d0"),
                        new("d7"),
                        new("d8"),
                        new("d3"),
                        new("d2"),
                        new("d9"),
                        new("d6"),
                        new("d1"),
                        new("d4"),
                        new("d5"),
                        new("3x"),
                        new("3"),
                        new("4"),
                        new("5"),
                        new("6"),
                        new("7"),
                        new("8"),
                        new("9"),
                        new("9b"),
                        new("10"),
                        new("2"),
                        new("11"),
                        new("12b"),
                        new("12c"),
                        new("12d"),
                        new("12"),
                        new("13"),
                        new("end_0"),
                        new("end_s0"),
                        new("end_s1"),
                        new("end_1"),
                        new("end_2"),
                        new("end_3"),
                        new("end_4"),
                        new("end_3b"),
                        new("end_3cb"),
                        new("end_3c"),
                        new("end_5"),
                        new("end_6"),
                    }
                }, {
                    "Celeste/2-OldSite-BSide",
                    new List<ReorderedName> {
                        new("start"),
                        new("00"),
                        new("01"),
                        new("01b"),
                        new("02b"),
                        new("02"),
                        new("03"),
                        new("04"),
                        new("05"),
                        new("06"),
                        new("07"),
                        new("08b"),
                        new("08"),
                        new("09"),
                        new("10"),
                        new("11"),
                        new("end"),
                    }
                }, {
                    "Celeste/2-OldSite-CSide",
                    new List<ReorderedName> {
                        new("00"),
                        new("01"),
                        new("02"),
                    }
                }, {
                    "Celeste/3-CelestialResort-Normal",
                    new List<ReorderedName> {
                        new("s0"),
                        new("s1"),
                        new("s2"),
                        new("s3"),
                        new("0x-a"),
                        new("00-a"),
                        new("02-a"),
                        new("02-b"),
                        new("01-b"),
                        new("00-b"),
                        new("00-c"),
                        new("0x-b"),
                        new("03-a"),
                        new("04-b"),
                        new("05-a"),
                        new("06-a"),
                        new("07-a"),
                        new("07-b"),
                        new("06-b"),
                        new("06-c"),
                        new("05-c"),
                        new("08-c"),
                        new("08-b"),
                        new("08-a"),
                        new("09-b"),
                        new("11-x"),
                        new("11-y"),
                        new("12-y"),
                        new("11-z"),
                        new("10-z"),
                        new("10-y"),
                        new("10-x"),
                        new("08-x"),
                        new("11-b"),
                        new("12-b"),
                        new("13-b"),
                        new("13-a"),
                        new("13-x"),
                        new("12-x"),
                        new("11-a"),
                        new("10-c"),
                        new("11-c"),
                        new("12-c"),
                        new("12-d"),
                        new("11-d"),
                        new("10-d"),
                        new("09-d"),
                        new("08-d"),
                        new("06-d"),
                        new("04-d"),
                        new("04-c"),
                        new("02-c"),
                        new("03-b"),
                        new("01-c"),
                        new("02-d"),
                        new("00-d"),
                        new("roof00"),
                        new("roof01"),
                        new("roof02"),
                        new("roof03"),
                        new("roof04"),
                        new("roof05"),
                        new("roof06b"),
                        new("roof06"),
                        new("roof07"),
                    }
                }, {
                    "Celeste/3-CelestialResort-BSide",
                    new List<ReorderedName> {
                        new("00"),
                        new("01"),
                        new("02"),
                        new("03"),
                        new("04"),
                        new("05"),
                        new("06"),
                        new("07"),
                        new("08"),
                        new("09"),
                        new("10"),
                        new("11"),
                        new("13"),
                        new("14"),
                        new("15"),
                        new("12"),
                        new("16"),
                        new("17"),
                        new("18"),
                        new("19"),
                        new("21"),
                        new("20"),
                        new("end"),
                    }
                }, {
                    "Celeste/3-CelestialResort-CSide",
                    new List<ReorderedName> {
                        new("00"),
                        new("01"),
                        new("02"),
                    }
                }, {
                    "Celeste/4-GoldenRidge-Normal",
                    new List<ReorderedName> {
                        new("a-00"),
                        new("a-01"),
                        new("a-01x"),
                        new("a-02"),
                        new("a-03"),
                        new("a-04"),
                        new("a-05"),
                        new("a-05x"),
                        new("a-06"),
                        new("a-07"),
                        new("a-08"),
                        new("a-10"),
                        new("a-11"),
                        new("a-09"),
                        new("b-00"),
                        new("b-01"),
                        new("b-02"),
                        new("b-05"),
                        new("b-04"),
                        new("b-06"),
                        new("b-07"),
                        new("b-03"),
                        new("b-sec"),
                        new("b-secb"),
                        new("b-08b"),
                        new("b-08"),
                        new("c-00"),
                        new("c-01"),
                        new("c-02"),
                        new("c-04"),
                        new("c-05"),
                        new("c-06"),
                        new("c-06b"),
                        new("c-09"),
                        new("c-07"),
                        new("c-08"),
                        new("c-10"),
                        new("d-00"),
                        new("d-00b"),
                        new("d-01"),
                        new("d-02"),
                        new("d-03"),
                        new("d-04"),
                        new("d-05"),
                        new("d-06"),
                        new("d-07"),
                        new("d-08"),
                        new("d-09"),
                        new("d-10"),
                    }
                }, {
                    "Celeste/4-GoldenRidge-BSide",
                    new List<ReorderedName> {
                        new("a-00"),
                        new("a-01"),
                        new("a-02"),
                        new("a-03"),
                        new("a-04"),
                        new("b-00"),
                        new("b-01"),
                        new("b-02"),
                        new("b-03"),
                        new("b-04"),
                        new("c-00"),
                        new("c-01"),
                        new("c-02"),
                        new("c-03"),
                        new("c-04"),
                        new("d-00"),
                        new("d-01"),
                        new("d-02"),
                        new("d-03"),
                        new("end"),
                    }
                }, {
                    "Celeste/4-GoldenRidge-CSide",
                    new List<ReorderedName> {
                        new("00"),
                        new("01"),
                        new("02"),
                    }
                }, {
                    "Celeste/5-MirrorTemple-Normal",
                    new List<ReorderedName> {
                        new("a-00b"),
                        new("a-00x"),
                        new("a-00d"),
                        new("a-00c"),
                        new("a-00"),
                        new("a-01"),
                        new("a-04"),
                        new("a-03"),
                        new("a-05"),
                        new("a-06"),
                        new("a-07"),
                        new("a-02"),
                        new("a-08"),
                        new("a-10"),
                        new("a-09"),
                        new("a-11"),
                        new("a-14"),
                        new("a-12"),
                        new("a-15"),
                        new("a-13"),
                        new("b-00"),
                        new("b-18"),
                        new("b-01"),
                        new("b-01c"),
                        new("b-20"),
                        new("b-21"),
                        new("b-01b"),
                        new("b-02"),
                        new("b-11"),
                        new("b-13"),
                        new("b-17"),
                        new("b-22"),
                        new("b-12"),
                        new("b-10"),
                        new("b-03"),
                        new("b-05"),
                        new("b-04"),
                        new("b-07"),
                        new("b-08"),
                        new("b-09"),
                        new("b-06"),
                        new("b-19"),
                        new("b-14"),
                        new("b-15"),
                        new("b-16"),
                        new("void"),
                        new("c-00"),
                        new("c-01"),
                        new("c-01b"),
                        new("c-01c"),
                        new("c-08b"),
                        new("c-08"),
                        new("c-10"),
                        new("c-12"),
                        new("c-07"),
                        new("c-11"),
                        new("c-09"),
                        new("c-13"),
                        new("d-00"),
                        new("d-01"),
                        new("d-15"),
                        new("d-13"),
                        new("d-04"),
                        new("d-09"),
                        new("d-07"),
                        new("d-05"),
                        new("d-06"),
                        new("d-02"),
                        new("d-03"),
                        new("d-19b"),
                        new("d-19"),
                        new("d-10"),
                        new("d-20"),
                        new("e-00"),
                        new("e-01"),
                        new("e-02"),
                        new("e-03"),
                        new("e-04"),
                        new("e-06"),
                        new("e-05"),
                        new("e-07"),
                        new("e-08"),
                        new("e-09"),
                        new("e-10"),
                        new("e-11"),
                    }
                }, {
                    "Celeste/5-MirrorTemple-BSide",
                    new List<ReorderedName> {
                        new("start"),
                        new("a-00"),
                        new("a-01"),
                        new("a-02"),
                        new("b-00"),
                        new("b-01"),
                        new("b-04"),
                        new("b-02"),
                        new("b-05"),
                        new("b-06"),
                        new("b-07"),
                        new("b-03"),
                        new("b-08"),
                        new("b-09"),
                        new("c-00"),
                        new("c-01"),
                        new("c-02"),
                        new("c-03"),
                        new("c-04"),
                        new("d-00"),
                        new("d-01"),
                        new("d-02"),
                        new("d-03"),
                        new("d-04"),
                        new("d-05"),
                    }
                }, {
                    "Celeste/5-MirrorTemple-CSide",
                    new List<ReorderedName> {
                        new("00"),
                        new("01"),
                        new("02"),
                    }
                }, {
                    "Celeste/6-Reflection-Normal",
                    new List<ReorderedName> {
                        new("start"),
                        new("00"),
                        new("01"),
                        new("02"),
                        new("03"),
                        new("02b"),
                        new("04"),
                        new("04b"),
                        new("04c"),
                        new("04e"),
                        new("04d"),
                        new("05"),
                        new("06"),
                        new("07"),
                        new("08b"),
                        new("08a"),
                        new("09"),
                        new("10b"),
                        new("10a"),
                        new("11"),
                        new("12b"),
                        new("12a"),
                        new("13"),
                        new("14b"),
                        new("14a"),
                        new("15"),
                        new("16b"),
                        new("16a"),
                        new("17"),
                        new("18b"),
                        new("18a"),
                        new("19"),
                        new("20"),
                        new("b-00"),
                        new("b-00b"),
                        new("b-00c"),
                        new("b-01"),
                        new("b-02"),
                        new("b-02b"),
                        new("b-03"),
                        new("boss-00"),
                        new("boss-01"),
                        new("boss-02"),
                        new("boss-03"),
                        new("boss-04"),
                        new("boss-05"),
                        new("boss-06"),
                        new("boss-07"),
                        new("boss-08"),
                        new("boss-09"),
                        new("boss-10"),
                        new("boss-11"),
                        new("boss-12"),
                        new("boss-13"),
                        new("boss-14"),
                        new("boss-15"),
                        new("boss-16"),
                        new("boss-17"),
                        new("boss-18"),
                        new("boss-19"),
                        new("boss-20"),
                        new("after-00"),
                        new("after-01"),
                        new("after-02"),
                    }
                }, {
                    "Celeste/6-Reflection-BSide",
                    new List<ReorderedName> {
                        new("a-00"),
                        new("a-01"),
                        new("a-02"),
                        new("a-03"),
                        new("a-04"),
                        new("a-05"),
                        new("a-06"),
                        new("b-00"),
                        new("b-01"),
                        new("b-02"),
                        new("b-03"),
                        new("b-04"),
                        new("b-05"),
                        new("b-06"),
                        new("b-07"),
                        new("b-08"),
                        new("b-10"),
                        new("c-00"),
                        new("c-01"),
                        new("c-02"),
                        new("c-03"),
                        new("c-04"),
                        new("d-00"),
                        new("d-01"),
                        new("d-02"),
                        new("d-03"),
                        new("d-04"),
                        new("d-05"),
                    }
                }, {
                    "Celeste/6-Reflection-CSide",
                    new List<ReorderedName> {
                        new("00"),
                        new("01"),
                        new("02"),
                    }
                }, {
                    "Celeste/7-Summit-Normal",
                    new List<ReorderedName> {
                        new("a-00-intro"),
                        new("a-00"),
                        new("a-01"),
                        new("a-02"),
                        new("a-02b"),
                        new("a-03"),
                        new("a-04"),
                        new("a-04b"),
                        new("a-05"),
                        new("a-06"),
                        new("b-00"),
                        new("b-01"),
                        new("b-02"),
                        new("b-02b"),
                        new("b-02e"),
                        new("b-02c"),
                        new("b-02d"),
                        new("b-03"),
                        new("b-04"),
                        new("b-05"),
                        new("b-06"),
                        new("b-07"),
                        new("b-08"),
                        new("b-09"),
                        new("c-00"),
                        new("c-01"),
                        new("c-02"),
                        new("c-03"),
                        new("c-03b"),
                        new("c-04"),
                        new("c-05"),
                        new("c-06"),
                        new("c-06b"),
                        new("c-06c"),
                        new("c-07"),
                        new("c-07b"),
                        new("c-08"),
                        new("c-09"),
                        new("d-00"),
                        new("d-01"),
                        new("d-01b"),
                        new("d-01c"),
                        new("d-01d"),
                        new("d-02"),
                        new("d-03"),
                        new("d-03b"),
                        new("d-04"),
                        new("d-05"),
                        new("d-05b"),
                        new("d-05x"),
                        new("d-06"),
                        new("d-07"),
                        new("d-08"),
                        new("d-09"),
                        new("d-10"),
                        new("d-10b"),
                        new("d-11"),
                        new("e-00b"),
                        new("e-00"),
                        new("e-01"),
                        new("e-01b"),
                        new("e-01c"),
                        new("e-03"),
                        new("e-02"),
                        new("e-04"),
                        new("e-05"),
                        new("e-06"),
                        new("e-07"),
                        new("e-08"),
                        new("e-09"),
                        new("e-11"),
                        new("e-12"),
                        new("e-10"),
                        new("e-10b"),
                        new("e-13"),
                        new("f-00"),
                        new("f-01"),
                        new("f-02"),
                        new("f-02b"),
                        new("f-04"),
                        new("f-03"),
                        new("f-05"),
                        new("f-06"),
                        new("f-07"),
                        new("f-08"),
                        new("f-08b"),
                        new("f-08d"),
                        new("f-08c"),
                        new("f-09"),
                        new("f-10"),
                        new("f-10b"),
                        new("f-11"),
                        new("g-00"),
                        new("g-00b"),
                        new("g-01"),
                        new("g-02"),
                        new("g-03"),
                        new("credits-city"),
                        new("credits-clouds"),
                        new("credits-dashes"),
                        new("credits-payphone"),
                        new("credits-prologue"),
                        new("credits-resort"),
                        new("credits-summit"),
                        new("credits-tree"),
                        new("credits-walking"),
                        new("credits-wallslide"),
                    }
                }, {
                    "Celeste/7-Summit-BSide",
                    new List<ReorderedName> {
                        new("a-00-intro"),
                        new("a-00"),
                        new("a-01"),
                        new("a-02"),
                        new("a-03"),
                        new("b-00"),
                        new("b-01"),
                        new("b-02"),
                        new("b-03"),
                        new("c-00"),
                        new("c-01"),
                        new("c-02"),
                        new("c-03"),
                        new("d-00"),
                        new("d-01"),
                        new("d-02"),
                        new("d-03"),
                        new("e-00"),
                        new("e-01"),
                        new("e-02"),
                        new("e-03"),
                        new("f-00"),
                        new("f-01"),
                        new("f-02"),
                        new("f-03"),
                        new("g-00"),
                        new("g-01"),
                        new("g-02"),
                        new("g-03"),
                    }
                }, {
                    "Celeste/7-Summit-CSide",
                    new List<ReorderedName> {
                        new("01"),
                        new("02"),
                        new("03"),
                    }
                }, {
                    "Celeste/8-Epilogue-Normal",
                    new List<ReorderedName> {
                        new("outside"),
                        new("bridge"),
                        new("secret"),
                        new("inside"),
                    }
                }, {
                    "Celeste/9-Core-Normal",
                    new List<ReorderedName> {
                        new("00"),
                        new("0x"),
                        new("01"),
                        new("02"),
                        new("a-00"),
                        new("a-01"),
                        new("a-02"),
                        new("a-03"),
                        new("b-00"),
                        new("b-01"),
                        new("b-02"),
                        new("b-03"),
                        new("b-04"),
                        new("b-05"),
                        new("b-06"),
                        new("b-07b"),
                        new("b-07"),
                        new("c-00"),
                        new("c-00b"),
                        new("c-01"),
                        new("c-02"),
                        new("c-03"),
                        new("c-03b"),
                        new("c-04"),
                        new("d-00"),
                        new("d-01"),
                        new("d-02"),
                        new("d-03"),
                        new("d-04"),
                        new("d-05"),
                        new("d-06"),
                        new("d-07"),
                        new("d-08"),
                        new("d-09"),
                        new("d-10"),
                        new("d-10b"),
                        new("d-10c"),
                        new("d-11"),
                        new("space"),
                    }
                }, {
                    "Celeste/9-Core-BSide",
                    new List<ReorderedName> {
                        new("00"),
                        new("01"),
                        new("a-00"),
                        new("a-01"),
                        new("a-02"),
                        new("a-03"),
                        new("a-04"),
                        new("a-05"),
                        new("b-00"),
                        new("b-01"),
                        new("b-02"),
                        new("b-03"),
                        new("b-04"),
                        new("b-05"),
                        new("c-01"),
                        new("c-02"),
                        new("c-03"),
                        new("c-04"),
                        new("c-05"),
                        new("c-06"),
                        new("c-08"),
                        new("c-07"),
                        new("space"),
                    }
                }, {
                    "Celeste/9-Core-CSide",
                    new List<ReorderedName> {
                        new("intro"),
                        new("00"),
                        new("01"),
                        new("02"),
                    }
                }, {
                    "Celeste/LostLevels-Normal",
                    new List<ReorderedName> {
                        new("intro-00-past"),
                        new("intro-01-future"),
                        new("intro-02-launch"),
                        new("intro-03-space"),
                        new("a-00"),
                        new("a-01"),
                        new("a-02"),
                        new("a-03"),
                        new("a-04"),
                        new("a-05"),
                        new("b-00"),
                        new("b-01"),
                        new("b-02"),
                        new("b-03"),
                        new("b-04"),
                        new("b-05"),
                        new("b-06"),
                        new("b-07"),
                        new("c-00"),
                        new("c-00b"),
                        new("c-01"),
                        new("c-02"),
                        new("c-alt-00"),
                        new("c-alt-01"),
                        new("c-03"),
                        new("d-00"),
                        new("d-02"),
                        new("d-01"),
                        new("d-03"),
                        new("d-04"),
                        new("d-05"),
                        new("e-00y"),
                        new("e-00yb"),
                        new("e-00z"),
                        new("e-00"),
                        new("e-00b"),
                        new("e-01"),
                        new("e-02"),
                        new("e-03"),
                        new("e-04"),
                        new("e-05"),
                        new("e-05b"),
                        new("e-05c"),
                        new("e-06"),
                        new("e-07"),
                        new("e-08"),
                        new("f-door"),
                        new("f-00"),
                        new("f-01"),
                        new("f-02"),
                        new("f-03"),
                        new("f-04"),
                        new("f-05"),
                        new("f-06"),
                        new("f-07"),
                        new("f-08"),
                        new("f-09"),
                        new("g-00"),
                        new("g-01"),
                        new("g-03"),
                        new("g-02"),
                        new("g-04"),
                        new("g-05"),
                        new("g-06", 28280, -8080),
                        new("h-00b"),
                        new("h-00"),
                        new("h-01"),
                        new("h-02"),
                        new("h-03"),
                        new("h-03b"),
                        new("h-04"),
                        new("h-04b"),
                        new("h-05"),
                        new("h-06"),
                        new("h-06b"),
                        new("h-07"),
                        new("h-08"),
                        new("h-09"),
                        new("h-10"),
                        new("i-00"),
                        new("i-00b"),
                        new("i-01"),
                        new("i-02"),
                        new("i-03"),
                        new("i-04"),
                        new("i-05"),
                        new("j-00"),
                        new("j-00b"),
                        new("j-01"),
                        new("j-02"),
                        new("j-03"),
                        new("j-04"),
                        new("j-05"),
                        new("j-06"),
                        new("j-07"),
                        new("j-08"),
                        new("j-09"),
                        new("j-10"),
                        new("j-11"),
                        new("j-12"),
                        new("j-13"),
                        new("j-14"),
                        new("j-14b"),
                        new("j-15"),
                        new("j-16"),
                        new("j-17"),
                        new("j-18"),
                        new("j-19"),
                        new("end-golden"),
                        new("end-cinematic"),
                        new("end-granny"),
                    }
                }, {
                    "BeefyUncleTorre/map/1-Normal",
                    new List<ReorderedName> {
                        new("crane-01"),
                        new("memory-00"),
                        new("ch1-peace-00"),
                        new("peace-28"),
                        new("peace-000"),
                        new("peace-0000"),
                        new("peace-01"),
                        new("peace-29"),
                        new("peace-02"),
                        new("peace-03"),
                        new("peace-04"),
                        new("peace-05"),
                        new("peace-06"),
                        new("peace-07"),
                        new("peace-08"),
                        new("peace-26"),
                        new("peace-10"),
                        new("peace-09"),
                        new("peace-11"),
                        new("ch2-peace-12"),
                        new("heat-00"),
                        new("heat-01"),
                        new("heat-00-01"),
                        new("heat-00-02"),
                        new("heat-00-03"),
                        new("heat-00-04"),
                        new("heat-00-07"),
                        new("heat-00-08"),
                        new("heat-00-05"),
                        new("heat-00-06"),
                        new("heat-02"),
                        new("peace-14"),
                        new("heat-04"),
                        new("peace-16"),
                        new("heat-06"),
                        new("peace-18"),
                        new("ch3-heat-08"),
                        new("memory-01"),
                        new("memory-01-b"),
                        new("cold-14"),
                        new("cold-00"),
                        new("heat-09"),
                        new("heat-10"),
                        new("heat-11"),
                        new("peace-27"),
                        new("cold-000"),
                        new("cold-01"),
                        new("cold-02"),
                        new("cold-03"),
                        new("cold-04"),
                        new("cold-10"),
                        new("cold-11"),
                        new("cold-16"),
                        new("cold-12"),
                        new("cold-05"),
                        new("cold-06"),
                        new("cold-07"),
                        new("cold-08"),
                        new("ch4-cold-09"),
                        new("cold-15"),
                        new("fall-00"),
                        new("fall-000"),
                        new("fall-0000"),
                        new("fall-00000"),
                        new("fall-01a"),
                        new("fall-02a"),
                        new("fall-03a"),
                        new("fall-04a"),
                        new("fall-05a"),
                        new("fall-06"),
                        new("fall-07"),
                        new("fall-17"),
                        new("fall-08a"),
                        new("fall-13"),
                        new("fall-14"),
                        new("fall-15"),
                        new("fall-16"),
                        new("fall-09a"),
                        new("fall-10a"),
                        new("fall-11a"),
                        new("fall-18"),
                        new("ch5-fall-12"),
                        new("memory-02b"),
                        new("memory-02c"),
                        new("memory-17"),
                        new("memory-02"),
                        new("memory-03"),
                        new("memory-18"),
                        new("memory-04"),
                        new("memory-05a"),
                        new("memory-19a"),
                        new("memory-06a"),
                        new("memory-07a"),
                        new("memory-14"),
                        new("memory-15"),
                        new("memory-16a"),
                        new("memory-08a"),
                        new("memory-09a"),
                        new("memory-10a"),
                        new("memory-11a"),
                        new("ch6-memory-12"),
                        new("memory-13"),
                        new("crane-02"),
                        new("crane-03"),
                        new("crane-04"),
                        new("crane-blue-01"),
                        new("crane-blue-02"),
                        new("crane-blue-03"),
                        new("crane-blue-04"),
                        new("crane-gold-01"),
                        new("crane-gold-02"),
                        new("crane-gold-03"),
                        new("crane-pink-01"),
                        new("crane-pink-02"),
                        new("crane-pink-03"),
                        new("crane-red-01"),
                        new("crane-red-02"),
                        new("crane-red-03"),
                        new("solace-00"),
                        new("solace-01"),
                        new("solace-02"),
                        new("solace-03"),
                        new("solace-04"),
                        new("solace-05"),
                        new("solace-06"),
                        new("solace-07"),
                    }
                },
            }
        }, {
            TeleportRoomCategory.Any, new Dictionary<string, List<ReorderedName>> {
                {
                    "Celeste/0-Intro-Normal",
                    new List<ReorderedName> {
                        new("0"),
                        new("1"),
                        new("2"),
                        new("3"),
                    }
                }, {
                    "Celeste/1-ForsakenCity-Normal",
                    new List<ReorderedName> {
                        new("1"),
                        new("2"),
                        new("3"),
                        new("4"),
                        new("3b"),
                        new("5"),
                        new("6"),
                        new("6a"),
                        new("6b"),
                        new("6c"),
                        new("7"),
                        new("8"),
                        new("8b"),
                        new("9"),
                        new("9b"),
                        new("10a"),
                        new("11", 3720, -2432),
                        new("12"),
                        new("12a"),
                        new("end"),
                    }
                }, {
                    "Celeste/2-OldSite-Normal",
                    new List<ReorderedName> {
                        new("start"),
                        new("0"),
                        new("1"),
                        new("d0", 792, 248),
                        new("d7"),
                        new("d8"),
                        new("d3", 1616, 600),
                        new("d2", 1592, 456),
                        new("d0", 952, 520),
                        new("1", 800, 168),
                        new("0", 632, 144),
                        new("3x"),
                        new("3"),
                        new("4"),
                        new("5"),
                        new("6"),
                        new("7"),
                        new("8"),
                        new("9"),
                        new("10"),
                        new("2", 992, -256),
                        new("11"),
                        new("12b"),
                        new("12"),
                        new("13"),
                        new("end_0"),
                        new("end_1"),
                        new("end_2"),
                        new("end_3"),
                        new("end_4"),
                        new("end_3b"),
                        new("end_5"),
                        new("end_6"),
                    }
                }, {
                    "Celeste/3-CelestialResort-Normal",
                    new List<ReorderedName> {
                        new("s0"),
                        new("s1"),
                        new("s2"),
                        new("s3"),
                        new("0x-a"),
                        new("00-a"),
                        new("02-a"),
                        new("02-b", 2576, -160),
                        new("03-a"),
                        new("05-a"),
                        new("06-a"),
                        new("07-a"),
                        new("07-b"),
                        new("06-b"),
                        new("06-c"),
                        new("08-c"),
                        new("08-b", 4624, -272),
                        new("07-b", 4328, -176),
                        new("07-a", 4068, -108),
                        new("08-a"),
                        new("09-b"),
                        new("09-b", 4969, -168),
                        new("10-x", 5264, 96),
                        new("11-x"),
                        new("11-y"),
                        new("11-z", 5552, 464),
                        new("10-z"),
                        new("10-y"),
                        new("10-x", 5272, 224),
                        new("09-b", 5008, 40),
                        new("09-b", 5240, -256),
                        new("10-c", 5224, -328),
                        new("11-c"),
                        new("12-c", 5624, -456),
                        new("12-d"),
                        new("11-d", 5608, -640),
                        new("10-d"),
                        new("10-c", 5000, -480),
                        new("09-b", 5064, -248),
                        new("11-b"),
                        new("12-b"),
                        new("13-b", 6000, -232),
                        new("13-a", 6032, -104),
                        new("13-x", 6224, 96),
                        new("12-x"),
                        new("11-a", 5648, 40),
                        new("09-b", 5288, -16),
                        new("09-d"),
                        new("08-d"),
                        new("06-d", 4312, -520),
                        new("04-d", 3680, -632),
                        new("02-d", 2936, -568),
                        new("00-d"),
                        new("roof00"),
                        new("roof01"),
                        new("roof02"),
                        new("roof03"),
                        new("roof04"),
                        new("roof05"),
                        new("roof06b"),
                        new("roof06"),
                        new("roof07"),
                    }
                }, {
                    "Celeste/4-GoldenRidge-Normal",
                    new List<ReorderedName> {
                        new("a-00"),
                        new("a-01"),
                        new("a-01x"),
                        new("a-02"),
                        new("a-03"),
                        new("a-04"),
                        new("a-05"),
                        new("a-06"),
                        new("a-07"),
                        new("a-08"),
                        new("a-09"),
                        new("b-00", 4416, -1016),
                        new("b-02", 4584, -1400),
                        new("b-05", 4664, -1496),
                        new("b-08b"),
                        new("b-08"),
                        new("c-00"),
                        new("c-02"),
                        new("c-04"),
                        new("c-05"),
                        new("c-06"),
                        new("c-09"),
                        new("c-07"),
                        new("c-08"),
                        new("d-00"),
                        new("d-01"),
                        new("d-02"),
                        new("d-03"),
                        new("d-04"),
                        new("d-05"),
                        new("d-06"),
                        new("d-07"),
                        new("d-08"),
                        new("d-09"),
                        new("d-10"),
                    }
                }, {
                    "Celeste/5-MirrorTemple-Normal",
                    new List<ReorderedName> {
                        new("a-00b"),
                        new("a-00d"),
                        new("a-00c"),
                        new("a-00"),
                        new("a-01", 1464, -16),
                        new("a-08", 1752, -528),
                        new("a-12", 2072, -536),
                        new("a-08", 2056, -408),
                        new("a-01", 1784, -344),
                        new("a-13"),
                        new("b-00"),
                        new("b-01"),
                        new("b-01b"),
                        new("b-02", 3872, -208),
                        new("b-11", 4168, -72),
                        new("b-13"),
                        new("b-17"),
                        new("b-22"),
                        new("b-06"),
                        new("b-19"),
                        new("b-14"),
                        new("b-16"),
                        new("void"),
                        new("c-00", -832, 1688),
                        new("c-01"),
                        new("c-01b"),
                        new("c-01c"),
                        new("c-08b"),
                        new("c-08"),
                        new("c-10"),
                        new("c-12"),
                        new("c-07"),
                        new("c-11"),
                        new("c-09"),
                        new("c-13"),
                        new("d-00", 3296, 2408),
                        new("d-01", 3296, 1888),
                        new("d-04", 2968, 1632),
                        new("d-19b", 2312, 1632),
                        new("d-19"),
                        new("d-19b", 2072, 1752),
                        new("d-10"),
                        new("d-20"),
                        new("e-00"),
                        new("e-01"),
                        new("e-02"),
                        new("e-03"),
                        new("e-04"),
                        new("e-06"),
                        new("e-05"),
                        new("e-07"),
                        new("e-08"),
                        new("e-09"),
                        new("e-10"),
                        new("e-11"),
                    }
                }, {
                    "Celeste/6-Reflection-Normal",
                    new List<ReorderedName> {
                        new("start"),
                        new("00"),
                        new("01"),
                        new("02"),
                        new("03"),
                        new("02", -1184, -1576),
                        new("02b"),
                        new("04", -1080, -2632),
                        new("05"),
                        new("06"),
                        new("07"),
                        new("08a"),
                        new("09"),
                        new("10b"),
                        new("11", 3320, -2968),
                        new("12b"),
                        new("13", 4248, -3032),
                        new("14a"),
                        new("15"),
                        new("16b"),
                        new("17"),
                        new("18b"),
                        new("19", 6960, -3040),
                        new("20"),
                        new("b-00"),
                        new("b-01"),
                        new("b-02", 10688, -2600),
                        new("b-02b", 11320, -928),
                        new("b-03"),
                        new("boss-00"),
                        new("boss-01"),
                        new("boss-02"),
                        new("boss-03"),
                        new("boss-04"),
                        new("boss-05"),
                        new("boss-06"),
                        new("boss-07"),
                        new("boss-08"),
                        new("boss-09"),
                        new("boss-10"),
                        new("boss-11"),
                        new("boss-12"),
                        new("boss-13"),
                        new("boss-14"),
                        new("boss-15"),
                        new("boss-16"),
                        new("boss-17"),
                        new("boss-18"),
                        new("boss-19"),
                        new("boss-20"),
                        new("after-00"),
                        new("after-01"),
                        new("after-02"),
                    }
                }, {
                    "Celeste/7-Summit-Normal",
                    new List<ReorderedName> {
                        new("a-00-intro"),
                        new("a-00"),
                        new("a-01"),
                        new("a-02"),
                        new("a-03"),
                        new("a-04"),
                        new("a-05"),
                        new("a-06"),
                        new("b-00"),
                        new("b-01"),
                        new("b-02"),
                        new("b-03"),
                        new("b-05"),
                        new("b-06"),
                        new("b-07"),
                        new("b-08"),
                        new("b-09"),
                        new("c-00"),
                        new("c-01"),
                        new("c-02"),
                        new("c-03"),
                        new("c-04"),
                        new("c-06", 7896, -5464),
                        new("c-07"),
                        new("c-08"),
                        new("c-09"),
                        new("d-00"),
                        new("d-01"),
                        new("d-01b"),
                        new("d-02"),
                        new("d-03"),
                        new("d-04"),
                        new("d-05"),
                        new("d-06"),
                        new("d-08"),
                        new("d-10"),
                        new("d-11"),
                        new("e-00b"),
                        new("e-00"),
                        new("e-02"),
                        new("e-03", 15288, -8880),
                        new("e-04"),
                        new("e-05"),
                        new("e-06"),
                        new("e-07"),
                        new("e-08", 18160, -9784),
                        new("e-10"),
                        new("e-10b"),
                        new("e-13"),
                        new("f-00"),
                        new("f-02"),
                        new("f-04"),
                        new("f-03"),
                        new("f-05"),
                        new("f-07", 23128, -11616),
                        new("f-08"),
                        new("f-09"),
                        new("f-10"),
                        new("f-10b"),
                        new("f-11"),
                        new("g-00"),
                        new("g-00b"),
                        new("g-01"),
                        new("g-02"),
                        new("g-03"),
                    }
                }, {
                    "Celeste/9-Core-Normal",
                    new List<ReorderedName> {
                        new("00"),
                        new("01"),
                        new("02"),
                        new("a-00"),
                        new("a-01"),
                        new("a-02"),
                        new("a-03"),
                        new("b-00", 2880, -832),
                        new("b-07b"),
                        new("b-07"),
                        new("c-00"),
                        new("c-01"),
                        new("c-02"),
                        new("c-03"),
                        new("c-04"),
                        new("d-00"),
                        new("d-01"),
                        new("d-02"),
                        new("d-03"),
                        new("d-04"),
                        new("d-05"),
                        new("d-06"),
                        new("d-07"),
                        new("d-08"),
                        new("d-09"),
                        new("d-10"),
                        new("d-10b"),
                        new("d-10c"),
                        new("d-11"),
                        new("space"),
                    }
                }, {
                    "Celeste/LostLevels-Normal",
                    new List<ReorderedName> {
                        new("intro-00-past"),
                        new("intro-01-future"),
                        new("intro-02-launch"),
                        new("intro-03-space"),
                        new("a-00"),
                        new("a-01"),
                        new("a-02"),
                        new("a-03"),
                        new("a-04"),
                        new("a-05"),
                        new("b-00"),
                        new("b-01"),
                        new("b-02"),
                        new("b-03"),
                        new("b-04"),
                        new("b-05"),
                        new("b-06"),
                        new("b-07"),
                        new("c-00"),
                        new("c-alt-00"),
                        new("c-alt-01"),
                        new("c-03"),
                        new("d-00", 12808, -2464),
                        new("d-02"),
                        new("d-05"),
                        new("e-00y"),
                        new("e-00yb"),
                        new("e-00z"),
                        new("e-00"),
                        new("e-00b"),
                        new("e-01"),
                        new("e-02"),
                        new("e-03"),
                        new("e-04"),
                        new("e-05"),
                        new("e-05b"),
                        new("e-05c"),
                        new("e-06"),
                        new("e-07"),
                        new("e-08"),
                        new("f-door"),
                        new("f-00"),
                        new("f-01"),
                        new("f-02"),
                        new("f-03"),
                        new("f-04"),
                        new("f-05"),
                        new("f-06"),
                        new("f-07"),
                        new("f-08"),
                        new("f-09"),
                        new("g-00"),
                        new("g-01"),
                        new("g-03"),
                        new("g-02"),
                        new("g-04"),
                        new("g-05"),
                        new("g-06", 28280, -8080),
                        new("h-00b"),
                        new("h-00"),
                        new("h-01"),
                        new("h-02"),
                        new("h-03"),
                        new("h-03b"),
                        new("h-04", 34800, -8592),
                        new("h-05"),
                        new("h-06"),
                        new("h-06b"),
                        new("h-07"),
                        new("h-08"),
                        new("h-09"),
                        new("h-10"),
                        new("i-00"),
                        new("i-00b"),
                        new("i-01"),
                        new("i-02"),
                        new("i-03"),
                        new("i-04"),
                        new("i-05"),
                        new("j-00"),
                        new("j-00b"),
                        new("j-01"),
                        new("j-02"),
                        new("j-03"),
                        new("j-04"),
                        new("j-05"),
                        new("j-06"),
                        new("j-07"),
                        new("j-08"),
                        new("j-09"),
                        new("j-10"),
                        new("j-11"),
                        new("j-12"),
                        new("j-13"),
                        new("j-14"),
                        new("j-14b"),
                        new("j-15"),
                        new("j-16"),
                        new("j-16", 81968, -10544),
                        new("j-16", 81584, -11944),
                        new("j-17"),
                        new("j-19"),
                        new("end-golden"),
                    }
                }, {
                    "BeefyUncleTorre/map/1-Normal",
                    new List<ReorderedName> {
                        new("crane-01"),
                        new("memory-00"),
                        new("ch1-peace-00", 621, 240),
                        new("peace-000"),
                        new("peace-01"),
                        new("peace-02"),
                        new("peace-03"),
                        new("peace-04", 1704, -8),
                        new("peace-05"),
                        new("peace-06"),
                        new("peace-07"),
                        new("peace-08"),
                        new("peace-09"),
                        new("peace-06", 2184, -336),
                        new("peace-11"),
                        new("ch2-peace-12"),
                        new("heat-00"),
                        new("heat-00-01"),
                        new("heat-00-02"),
                        new("heat-00-03"),
                        new("heat-00-04", 3304, 2400),
                        new("heat-00-05"),
                        new("heat-00-06"),
                        new("heat-02"),
                        new("peace-14"),
                        new("heat-04"),
                        new("peace-16"),
                        new("heat-05", 4504, 2072),
                        new("heat-06"),
                        new("peace-18"),
                        new("ch3-heat-08"),
                        new("memory-01"),
                        new("cold-14"),
                        new("cold-00"),
                        new("heat-09"),
                        new("cold-01"),
                        new("cold-02"),
                        new("cold-03"),
                        new("cold-04"),
                        new("cold-05"),
                        new("cold-06"),
                        new("cold-07"),
                        new("cold-08"),
                        new("ch4-cold-09"),
                        new("fall-00"),
                        new("fall-000"),
                        new("fall-0000"),
                        new("fall-01a"),
                        new("fall-03a"),
                        new("fall-04a"),
                        new("fall-05a"),
                        new("fall-07"),
                        new("fall-08a"),
                        new("fall-13"),
                        new("fall-14"),
                        new("fall-15", -6416, 448),
                        new("fall-16", -6520, 56),
                        new("fall-15", -6672, 144),
                        new("fall-09a"),
                        new("fall-10a"),
                        new("fall-11a"),
                        new("fall-18"),
                        new("ch5-fall-12"),
                        new("memory-02b"),
                        new("memory-02c"),
                        new("memory-02"),
                        new("memory-03"),
                        new("memory-04"),
                        new("memory-05a"),
                        new("memory-06a"),
                        new("memory-07a"),
                        new("memory-14", -12232, -184),
                        new("memory-15"),
                        new("memory-16a"),
                        new("memory-08a"),
                        new("memory-09a"),
                        new("memory-10a"),
                        new("memory-11a"),
                        new("ch6-memory-12"),
                        new("memory-13"),
                    }
                },
            }
        }
    };

    private static readonly Dictionary<TeleportRoomCategory, Dictionary<AreaKey, List<ReorderedData>>> ReorderLevelDataDict = new() {
        {TeleportRoomCategory.Default, new Dictionary<AreaKey, List<ReorderedData>>()},
        {TeleportRoomCategory.Any, new Dictionary<AreaKey, List<ReorderedData>>()}
    };

    public static List<ReorderedData> GetReorderedLevelDataList(Level level, TeleportRoomCategory? teleportRoomCategory = null) {
        teleportRoomCategory ??= ModSettings.TeleportRoomCategory;

        var reorderedLevelNames = ReorderedDataDict[teleportRoomCategory.Value];
        var reorderedLevelData = ReorderLevelDataDict[teleportRoomCategory.Value];

        AreaKey areaKey = level.Session.Area;
        List<LevelData> origLevelDataList = level.Session.MapData.Levels;

        if (reorderedLevelData.ContainsKey(areaKey)) {
            return reorderedLevelData[areaKey];
        }

        List<ReorderedData> result = new();
        string sidMode = $"{areaKey.SID}-{areaKey.Mode}";

        if (!reorderedLevelNames.ContainsKey(sidMode) && teleportRoomCategory.Value != TeleportRoomCategory.Default) {
            reorderedLevelNames = ReorderedDataDict[TeleportRoomCategory.Default];
        }

        if (reorderedLevelNames.ContainsKey(sidMode)) {
            List<ReorderedName> levelNames = reorderedLevelNames[sidMode];
            foreach (ReorderedName reorderedName in levelNames) {
                LevelData levelData = origLevelDataList.FirstOrDefault(data => data.Name == reorderedName.LevelName);
                if (levelData != null) {
                    result.Add(new ReorderedData(levelData, reorderedName.RespawnPoint));
                }
            }
        }

        if (result.Count > 0) {
            return reorderedLevelData[areaKey] = result;
        } else {
            return reorderedLevelData[areaKey] = origLevelDataList.Select(data => new ReorderedData(data)).ToList();
        }
    }
}